// Pictionary word list: the word the drawer gets, followed by any other
// answers that should also count as correct.
//
// You do NOT need to list these as alternates, they're handled automatically:
//   - Capitalization, extra spaces, punctuation ("Hot-Dog!" = "hot dog")
//   - "a"/"an"/"the" in front ("a banana" = "banana")
//   - Spaces vs no spaces ("hotdog" = "hot dog")
//   - Regular plurals ("bananas", "cherries", "boxes")
//   - A single-letter typo on words 5+ letters long ("bananna", "pengiun")
//
// DO list: synonyms, related names people would reasonably type
// (monkey -> ape), and irregular plurals (mouse -> mice).
//
// To add a word: add a line like  "word": ["alternate one", "alternate two"],
// To remove one: delete its line. Words are picked with no repeats until
// every word has been used once (tracked in Supabase, shared by the team).
window.PICTIONARY_WORDS = {
  // Animals
  "monkey": ["ape", "orangutan", "chimp", "chimpanzee", "gorilla", "baboon"],
  "cat": ["kitty", "kitten"],
  "dog": ["puppy", "pup", "doggo", "doggy"],
  "fish": ["goldfish"],
  "bird": ["birdie"],
  "snake": ["serpent", "cobra", "python"],
  "spider": ["tarantula", "spiderweb", "spider web"],
  "snail": ["slug"],
  "turtle": ["tortoise"],
  "octopus": ["squid", "kraken"],
  "whale": ["blue whale", "orca"],
  "shark": [],
  "penguin": [],
  "elephant": [],
  "giraffe": [],
  "lion": [],
  "pig": ["piggy", "hog", "swine", "piglet"],
  "cow": ["cattle", "bull"],
  "bee": ["bumblebee", "honeybee", "wasp"],
  "butterfly": ["moth"],
  "frog": ["toad"],
  "owl": [],
  "bat": ["vampire bat"],
  "dinosaur": ["dino", "t rex", "trex", "tyrannosaurus", "brontosaurus"],
  "mouse": ["mice", "rat"],
  "rabbit": ["bunny", "hare"],
  "bear": ["teddy bear", "grizzly"],
  "duck": ["duckling", "rubber duck"],
  "chicken": ["hen", "rooster"],
  "horse": ["pony"],
  "bug": ["insect", "beetle", "ladybug", "ant"],

  // Food
  "banana": [],
  "apple": [],
  "pizza": ["pizza slice", "slice of pizza"],
  "pineapple": [],
  "carrot": [],
  "ice cream": ["ice cream cone", "cone", "gelato"],
  "cake": ["birthday cake", "cupcake"],
  "donut": ["doughnut"],
  "hamburger": ["burger", "cheeseburger"],
  "hot dog": ["sausage"],
  "cookie": ["biscuit"],
  "egg": ["fried egg"],
  "cheese": [],
  "taco": [],
  "popcorn": [],
  "spaghetti": ["pasta", "noodles"],
  "sandwich": [],
  "watermelon": ["melon"],
  "grapes": ["grape"],
  "cherry": [],
  "lemon": ["lime"],
  "strawberry": [],
  "mushroom": ["toadstool", "shroom"],

  // Nature and weather
  "tree": [],
  "sun": ["sunshine"],
  "moon": ["crescent", "crescent moon"],
  "star": [],
  "cloud": [],
  "rainbow": [],
  "lightning": ["lightning bolt", "bolt", "thunder", "storm"],
  "volcano": [],
  "mountain": ["hill"],
  "island": [],
  "beach": [],
  "cactus": ["cacti"],
  "flower": ["rose", "daisy", "tulip"],
  "snowflake": ["snow"],
  "tornado": ["twister"],

  // Vehicles and places
  "rocket": ["spaceship", "rocketship", "space shuttle"],
  "car": ["automobile"],
  "bicycle": ["bike"],
  "airplane": ["plane", "jet", "aeroplane"],
  "boat": ["ship", "sailboat"],
  "train": ["locomotive"],
  "fire truck": ["fire engine"],
  "house": ["home", "cabin"],
  "castle": ["palace", "fort"],
  "tent": [],
  "igloo": [],
  "pyramid": [],
  "bridge": [],
  "windmill": [],
  "lighthouse": [],
  "traffic light": ["stoplight", "stop light", "traffic signal"],

  // Things
  "guitar": [],
  "drum": ["drum set", "drum kit"],
  "umbrella": [],
  "glasses": ["eyeglasses", "spectacles", "sunglasses"],
  "hat": ["cap", "top hat"],
  "shoe": ["sneaker", "boot"],
  "clock": ["alarm clock", "watch"],
  "key": [],
  "lightbulb": ["bulb", "idea"],
  "computer": ["laptop", "pc", "monitor"],
  "phone": ["cell phone", "smartphone", "iphone", "mobile"],
  "coffee": ["coffee cup", "coffee mug", "mug", "latte"],
  "book": [],
  "pencil": ["pen", "crayon"],
  "scissors": [],
  "ladder": [],
  "snowman": [],
  "ghost": [],
  "robot": [],
  "dragon": [],
  "unicorn": [],
  "alien": ["ufo", "martian", "extraterrestrial"],
  "pirate": [],
  "crown": ["tiara"],
  "sword": ["dagger"],
  "campfire": ["fire", "bonfire"],
  "anchor": [],
  "kite": [],
  "balloon": [],
  "gift": ["present", "package"],
  "candle": [],
  "bell": [],
  "magnet": [],
  "trophy": ["award"],
  "skateboard": [],
  "toilet": [],
  "bed": [],
  "chair": ["stool"],
  "lamp": [],
  "toothbrush": [],
  "headphones": ["headset", "earphones"],
  "camera": [],
  "television": ["tv"],
  "microphone": ["mic"],
  "magnifying glass": ["magnifier"],
  "backpack": ["bookbag", "rucksack"],
  "envelope": ["letter", "mail", "email"],
  "treasure chest": ["treasure", "chest"],
  "tooth": ["teeth", "molar"],
  "eye": ["eyeball"],
  "brain": [],
  "heart": ["love"],
  "skull": ["skeleton"],
};
